// <auto-generated />
using System;
using MediatR.Usage.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediatR.Usage.Api.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20230303120443_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediatR.Usage.Api.Data.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateOfBirth = new DateTime(2023, 3, 3, 17, 34, 43, 874, DateTimeKind.Local).AddTicks(4395),
                            Email = "testmohit@gmail.com",
                            FirstName = "Mohit",
                            LastName = "Yadav"
                        },
                        new
                        {
                            ID = 2,
                            DateOfBirth = new DateTime(2023, 3, 3, 17, 34, 43, 874, DateTimeKind.Local).AddTicks(4406),
                            Email = "testankitsharma@gmail.com",
                            FirstName = "Ankit",
                            LastName = "Sharma"
                        });
                });

            modelBuilder.Entity("MediatR.Usage.Api.Data.Models.Teacher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "testramesh@gmail.com",
                            FirstName = "Ramesh",
                            LastName = "Kumar",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            ID = 2,
                            Email = "testamitsharma@gmail.com",
                            FirstName = "Amit ",
                            LastName = "Sharma",
                            PhoneNumber = "1234517890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
